# Site settings
title: "Ravindra Saxena"
description: "A description of my awesome project."
baseurl: "/my-project" # the subpath of your site, e.g. "/blog"
url: "https://username.github.io" # the base hostname & protocol for your site
repository: "username/my-project" # GitHub repo name for issue links etc

# Theme settings
# You must specify a theme or remote_theme
theme: jekyll-theme-minimal # Example default theme
# remote_theme: mmistakes/so-simple-theme # Use this line instead for a remote theme

# Build settings
markdown: kramdown
# Optional: Exclude files from processing by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/


